/**
 * @file capi/adaboost.h
 *
 * This is an autogenerated header file for functions specified to the %NAME%
 * binding to be called by Go.
 */
#ifndef GO_adaboost_H
#define GO_adaboost_H

#include <stddef.h>

#if defined(__cplusplus) || defined(c_plusplus)

extern "C"
{
#endif

extern void mlpackAdaboost();

// Any definitions of methods for dealing with model pointers will be put below
// this comment, if needed.

// Set the pointer to a AdaBoostModel parameter.
extern void mlpackSetAdaBoostModelPtr(const char* identifier, void* value);

// Get the pointer to a AdaBoostModel parameter.
extern void* mlpackGetAdaBoostModelPtr(const char* identifier);


#if defined(__cplusplus) || defined(c_plusplus)
}
#endif

#endif
