/**
 * @file capi/approx_kfn.h
 *
 * This is an autogenerated header file for functions specified to the %NAME%
 * binding to be called by Go.
 */
#ifndef GO_approx_kfn_H
#define GO_approx_kfn_H

#include <stddef.h>

#if defined(__cplusplus) || defined(c_plusplus)

extern "C"
{
#endif

extern void mlpackApproxKfn();

// Any definitions of methods for dealing with model pointers will be put below
// this comment, if needed.

// Set the pointer to a ApproxKFNModel parameter.
extern void mlpackSetApproxKFNModelPtr(const char* identifier, void* value);

// Get the pointer to a ApproxKFNModel parameter.
extern void* mlpackGetApproxKFNModelPtr(const char* identifier);


#if defined(__cplusplus) || defined(c_plusplus)
}
#endif

#endif
