/**
 * @file capi/decision_stump.h
 *
 * This is an autogenerated header file for functions specified to the %NAME%
 * binding to be called by Go.
 */
#ifndef GO_decision_stump_H
#define GO_decision_stump_H

#include <stddef.h>

#if defined(__cplusplus) || defined(c_plusplus)

extern "C"
{
#endif

extern void mlpackDecisionStump();

// Any definitions of methods for dealing with model pointers will be put below
// this comment, if needed.

// Set the pointer to a DSModel parameter.
extern void mlpackSetDSModelPtr(const char* identifier, void* value);

// Get the pointer to a DSModel parameter.
extern void* mlpackGetDSModelPtr(const char* identifier);


#if defined(__cplusplus) || defined(c_plusplus)
}
#endif

#endif
