/**
 * @file capi/fastmks.h
 *
 * This is an autogenerated header file for functions specified to the %NAME%
 * binding to be called by Go.
 */
#ifndef GO_fastmks_H
#define GO_fastmks_H

#include <stddef.h>

#if defined(__cplusplus) || defined(c_plusplus)

extern "C"
{
#endif

extern void mlpackFastmks(void* params, void* timers);

// Any definitions of methods for dealing with model pointers will be put below
// this comment, if needed.

// Set the pointer to a FastMKSModel parameter.
extern void mlpackSetFastMKSModelPtr(void* params,
                                           const char* identifier,
                                           void* value);

// Get the pointer to a FastMKSModel parameter.
extern void* mlpackGetFastMKSModelPtr(void* params,
                                            const char* identifier);


#if defined(__cplusplus) || defined(c_plusplus)
}
#endif

#endif
