/**
 * @file capi/gmm_probability.h
 *
 * This is an autogenerated header file for functions specified to the %NAME%
 * binding to be called by Go.
 */
#ifndef GO_gmm_probability_H
#define GO_gmm_probability_H

#include <stddef.h>

#if defined(__cplusplus) || defined(c_plusplus)

extern "C"
{
#endif

extern void mlpackGmmProbability();

// Any definitions of methods for dealing with model pointers will be put below
// this comment, if needed.

// Set the pointer to a GMM parameter.
extern void mlpackSetGMMPtr(const char* identifier, void* value);

// Get the pointer to a GMM parameter.
extern void* mlpackGetGMMPtr(const char* identifier);


#if defined(__cplusplus) || defined(c_plusplus)
}
#endif

#endif
