/**
 * @file capi/hmm_viterbi.h
 *
 * This is an autogenerated header file for functions specified to the %NAME%
 * binding to be called by Go.
 */
#ifndef GO_hmm_viterbi_H
#define GO_hmm_viterbi_H

#include <stddef.h>

#if defined(__cplusplus) || defined(c_plusplus)

extern "C"
{
#endif

extern void mlpackHmmViterbi();

// Any definitions of methods for dealing with model pointers will be put below
// this comment, if needed.

// Set the pointer to a HMMModel parameter.
extern void mlpackSetHMMModelPtr(const char* identifier, void* value);

// Get the pointer to a HMMModel parameter.
extern void* mlpackGetHMMModelPtr(const char* identifier);


#if defined(__cplusplus) || defined(c_plusplus)
}
#endif

#endif
