/**
 * @file capi/image_converter.h
 *
 * This is an autogenerated header file for functions specified to the %NAME%
 * binding to be called by Go.
 */
#ifndef GO_image_converter_H
#define GO_image_converter_H

#include <stddef.h>

#if defined(__cplusplus) || defined(c_plusplus)

extern "C"
{
#endif

extern void mlpackImageConverter(void* params, void* timers);

// Any definitions of methods for dealing with model pointers will be put below
// this comment, if needed.


#if defined(__cplusplus) || defined(c_plusplus)
}
#endif

#endif
