/**
 * @file capi/kde.h
 *
 * This is an autogenerated header file for functions specified to the %NAME%
 * binding to be called by Go.
 */
#ifndef GO_kde_H
#define GO_kde_H

#include <stddef.h>

#if defined(__cplusplus) || defined(c_plusplus)

extern "C"
{
#endif

extern void mlpackKde();

// Any definitions of methods for dealing with model pointers will be put below
// this comment, if needed.

// Set the pointer to a KDEModel parameter.
extern void mlpackSetKDEModelPtr(const char* identifier, void* value);

// Get the pointer to a KDEModel parameter.
extern void* mlpackGetKDEModelPtr(const char* identifier);


#if defined(__cplusplus) || defined(c_plusplus)
}
#endif

#endif
