/**
 * @file capi/kfn.h
 *
 * This is an autogenerated header file for functions specified to the %NAME%
 * binding to be called by Go.
 */
#ifndef GO_kfn_H
#define GO_kfn_H

#include <stddef.h>

#if defined(__cplusplus) || defined(c_plusplus)

extern "C"
{
#endif

extern void mlpackKfn(void* params, void* timers);

// Any definitions of methods for dealing with model pointers will be put below
// this comment, if needed.

// Set the pointer to a KFNModel parameter.
extern void mlpackSetKFNModelPtr(void* params,
                                           const char* identifier,
                                           void* value);

// Get the pointer to a KFNModel parameter.
extern void* mlpackGetKFNModelPtr(void* params,
                                            const char* identifier);


#if defined(__cplusplus) || defined(c_plusplus)
}
#endif

#endif
