/**
 * @file capi/krann.h
 *
 * This is an autogenerated header file for functions specified to the %NAME%
 * binding to be called by Go.
 */
#ifndef GO_krann_H
#define GO_krann_H

#include <stddef.h>

#if defined(__cplusplus) || defined(c_plusplus)

extern "C"
{
#endif

extern void mlpackKrann();

// Any definitions of methods for dealing with model pointers will be put below
// this comment, if needed.

// Set the pointer to a RANNModel parameter.
extern void mlpackSetRANNModelPtr(const char* identifier, void* value);

// Get the pointer to a RANNModel parameter.
extern void* mlpackGetRANNModelPtr(const char* identifier);


#if defined(__cplusplus) || defined(c_plusplus)
}
#endif

#endif
