/**
 * @file capi/linear_svm.h
 *
 * This is an autogenerated header file for functions specified to the %NAME%
 * binding to be called by Go.
 */
#ifndef GO_linear_svm_H
#define GO_linear_svm_H

#include <stddef.h>

#if defined(__cplusplus) || defined(c_plusplus)

extern "C"
{
#endif

extern void mlpackLinearSvm();

// Any definitions of methods for dealing with model pointers will be put below
// this comment, if needed.

// Set the pointer to a LinearSVMModel parameter.
extern void mlpackSetLinearSVMModelPtr(const char* identifier, void* value);

// Get the pointer to a LinearSVMModel parameter.
extern void* mlpackGetLinearSVMModelPtr(const char* identifier);


#if defined(__cplusplus) || defined(c_plusplus)
}
#endif

#endif
