/**
 * @file capi/nmf.h
 *
 * This is an autogenerated header file for functions specified to the %NAME%
 * binding to be called by Go.
 */
#ifndef GO_nmf_H
#define GO_nmf_H

#include <stddef.h>

#if defined(__cplusplus) || defined(c_plusplus)

extern "C"
{
#endif

extern void mlpackNmf(void* params, void* timers);

// Any definitions of methods for dealing with model pointers will be put below
// this comment, if needed.


#if defined(__cplusplus) || defined(c_plusplus)
}
#endif

#endif
