/**
 * @file capi/random_forest.h
 *
 * This is an autogenerated header file for functions specified to the %NAME%
 * binding to be called by Go.
 */
#ifndef GO_random_forest_H
#define GO_random_forest_H

#include <stddef.h>

#if defined(__cplusplus) || defined(c_plusplus)

extern "C"
{
#endif

extern void mlpackRandomForest();

// Any definitions of methods for dealing with model pointers will be put below
// this comment, if needed.

// Set the pointer to a RandomForestModel parameter.
extern void mlpackSetRandomForestModelPtr(const char* identifier, void* value);

// Get the pointer to a RandomForestModel parameter.
extern void* mlpackGetRandomForestModelPtr(const char* identifier);


#if defined(__cplusplus) || defined(c_plusplus)
}
#endif

#endif
