/**
 * @file capi/softmax_regression.h
 *
 * This is an autogenerated header file for functions specified to the %NAME%
 * binding to be called by Go.
 */
#ifndef GO_softmax_regression_H
#define GO_softmax_regression_H

#include <stddef.h>

#if defined(__cplusplus) || defined(c_plusplus)

extern "C"
{
#endif

extern void mlpackSoftmaxRegression();

// Any definitions of methods for dealing with model pointers will be put below
// this comment, if needed.

// Set the pointer to a SoftmaxRegression parameter.
extern void mlpackSetSoftmaxRegressionPtr(const char* identifier, void* value);

// Get the pointer to a SoftmaxRegression parameter.
extern void* mlpackGetSoftmaxRegressionPtr(const char* identifier);


#if defined(__cplusplus) || defined(c_plusplus)
}
#endif

#endif
