/**
 * @file capi/test_go_binding.h
 *
 * This is an autogenerated header file for functions specified to the %NAME%
 * binding to be called by Go.
 */
#ifndef GO_test_go_binding_H
#define GO_test_go_binding_H

#include <stddef.h>

#if defined(__cplusplus) || defined(c_plusplus)

extern "C"
{
#endif

extern void mlpackTestGoBinding(void* params, void* timers);

// Any definitions of methods for dealing with model pointers will be put below
// this comment, if needed.

// Set the pointer to a GaussianKernel parameter.
extern void mlpackSetGaussianKernelPtr(void* params,
                                           const char* identifier,
                                           void* value);

// Get the pointer to a GaussianKernel parameter.
extern void* mlpackGetGaussianKernelPtr(void* params,
                                            const char* identifier);


#if defined(__cplusplus) || defined(c_plusplus)
}
#endif

#endif
